### ISSUE TITLE
Specs don't run

### ISSUE THREAD

**Issue by richardhp** [ib-ruby/ib-api#1]
I don't know if I'm missing something, but when I try and run the specs it says it cannot:

```ruby
require "core"
```

And then the core spec does not run because it fails on:

```ruby
RSpec.describe Core do
```

Is this "core" library another dependency which I don't have?

**Comment by topofocus** [comment]
Hi,
this is a hint, that your copy has not been synchronized  with the master branch. 

BTW. This library has been renamed from ib-core.

**Comment by richardhp** [comment]
Ok yeah I just did a git pull and that sorted it, thanks
