### ISSUE TITLE
problem with JPY futures options

### ISSUE THREAD

**Issue by JothamB** [ib-ruby/ib-api#12]
i run this code to get contract data for a specific JPY futures option:

`ib = IB::Connection.new(:port => 7497) do |gw|
	gw.subscribe(:Alert) {|msg| puts msg.to_human}
	gw.subscribe(:ContractData) {|msg| puts msg.to_human}
end
ib.send_message(:RequestMarketDataType, :market_data_type => :real_time)

c = IB::FutureOption.new(symbol: "JPY", exchange: "GLOBEX", trading_class: "JPU", expiry: "20210305", strike: 0.01, right: "C")
ib.send_message(:RequestContractData, contract: c)
sleep 999999`

and this is the output:

<Contract <Option: JPY 20210305 call 0.0119 GLOBEX USD>   <ContractDetails  Japanese yen, --> JPU, Underlying:JYH1[FUT](225390000), md_size_multiplier:1, min_tick:0.0000005, price_magnifier:1, valid exchanges: GLOBEX; order types: ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,RFQ,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF >>
<Contract <Option: JPY 20210305 call 0.0113 GLOBEX USD>   <ContractDetails  Japanese yen, --> JPU, Underlying:JYH1[FUT](225390000), md_size_multiplier:1, min_tick:0.0000005, price_magnifier:1, valid exchanges: GLOBEX; order types: ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,RFQ,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF >>
<Contract <Option: JPY 20210305 call 0.0114 GLOBEX USD>   <ContractDetails  Japanese yen, --> JPU, Underlying:JYH1[FUT](225390000), md_size_multiplier:1, min_tick:0.0000005, price_magnifier:1, valid exchanges: GLOBEX; order types: ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,RFQ,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF >>
<Contract <Option: JPY 20210305 call 0.0115 GLOBEX USD>   <ContractDetails  Japanese yen, --> JPU, Underlying:JYH1[FUT](225390000), md_size_multiplier:1, min_tick:0.0000005, price_magnifier:1, valid exchanges: GLOBEX; order types: ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,RFQ,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF >>
<Contract <Option: JPY 20210305 call 0.0116 GLOBEX USD>   <ContractDetails  Japanese yen, --> JPU, Underlying:JYH1[FUT](225390000), md_size_multiplier:1, min_tick:0.0000005, price_magnifier:1, valid exchanges: GLOBEX; order types: ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,RFQ,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF >>
<Contract <Option: JPY 20210305 call 0.01025 GLOBEX USD>   <ContractDetails  Japanese yen, --> JPU, Underlying:JYH1[FUT](225390000), md_size_multiplier:1, min_tick:0.0000005, price_magnifier:1, valid exchanges: GLOBEX; order types: ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,RFQ,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF >>
<Contract <Option: JPY 20210305 call 0.01035 GLOBEX USD>   <ContractDetails  Japanese yen, --> JPU, Underlying:JYH1[FUT](225390000), md_size_multiplier:1, min_tick:0.0000005, price_magnifier:1, valid exchanges: GLOBEX; order types: ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,RFQ,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF >>

seems like i get all the strikes although i created a FutureOption with a specific strike.
the problem occurred with live/demo accounts on tws/gateway

when i run the same code for EUR futures option i get correct output:

<Contract <Option: EUR 20210305 call 1.22 GLOBEX USD>   <ContractDetails  European Monetary Union Euro, --> EUU, Underlying:ECH1[FUT](225389915), md_size_multiplier:1, min_tick:0.00005, price_magnifier:1, valid exchanges: GLOBEX; order types: ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,RFQ,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF >>
No subscribers for message IB::Messages::Incoming::ContractDataEnd!

if you can look into it and figure out the problem that is great.
if you want me to contact you so we can test it on my system with my subscription that is great as well.

**Comment by topofocus** [comment]
You really should use the extensions.
```ruby
 c = IB::FutureOption.new(symbol: "JPY", exchange: "GLOBEX", trading_class: "JPU", expiry: "20210305", stri
ke: 0.01, right: "C")
3.0.0 :004 > z =  c.verify
<Option: JPY 20210305 call 0.01 GLOBEX > --> No ContractData recieved 
 => [] 

## omit the strike argument  ... correct strikes are: 0.0101 or 0.0104 : 

3.0.0 :006 > c = IB::FutureOption.new(symbol: "JPY", exchange: "GLOBEX", trading_class: "JPU", expiry: "20210305", right: "C")
 z =  c.verify
<Option: JPY 20210305 call 0.0101 GLOBEX USD>
<Option: JPY 20210305 call 0.0104 GLOBEX USD>
<Option: JPY 20210305 call 0.01005 GLOBEX USD>
<Option: JPY 20210305 call 0.0093 GLOBEX USD>
<Option: JPY 20210305 call 0.0108 GLOBEX USD>
<Option: JPY 20210305 call 0.0099 GLOBEX USD>
<Option: JPY 20210305 call 0.00985 GLOBEX USD>
<Option: JPY 20210305 call 0.0102 GLOBEX USD>
<Option: JPY 20210305 call 0.00995 GLOBEX USD>
<Option: JPY 20210305 call 0.0094 GLOBEX USD>
<Option: JPY 20210305 call 0.009 GLOBEX USD>
<Option: JPY 20210305 call 0.00935 GLOBEX USD>
<Option: JPY 20210305 call 0.0091 GLOBEX USD>
<Option: JPY 20210305 call 0.0103 GLOBEX USD>
<Option: JPY 20210305 call 0.0106 GLOBEX USD>
<Option: JPY 20210305 call 0.0095 GLOBEX USD>
<Option: JPY 20210305 call 0.011 GLOBEX USD>
<Option: JPY 20210305 call 0.00955 GLOBEX USD>
<Option: JPY 20210305 call 0.0086 GLOBEX USD>
<Option: JPY 20210305 call 0.0082 GLOBEX USD>
<Option: JPY 20210305 call 0.0098 GLOBEX USD>
<Option: JPY 20210305 call 0.0097 GLOBEX USD>
<Option: JPY 20210305 call 0.0087 GLOBEX USD>
<Option: JPY 20210305 call 0.00915 GLOBEX USD>
<Option: JPY 20210305 call 0.0084 GLOBEX USD>
<Option: JPY 20210305 call 0.0096 GLOBEX USD>
<Option: JPY 20210305 call 0.0085 GLOBEX USD>
<Option: JPY 20210305 call 0.00925 GLOBEX USD>
<Option: JPY 20210305 call 0.00975 GLOBEX USD>
<Option: JPY 20210305 call 0.0089 GLOBEX USD>
<Option: JPY 20210305 call 0.0105 GLOBEX USD>
<Option: JPY 20210305 call 0.0083 GLOBEX USD>
<Option: JPY 20210305 call 0.0088 GLOBEX USD>
<Option: JPY 20210305 call 0.01 GLOBEX USD>
<Option: JPY 20210305 call 0.00945 GLOBEX USD>
<Option: JPY 20210305 call 0.00965 GLOBEX USD>
<Option: JPY 20210305 call 0.01015 GLOBEX USD>
<Option: JPY 20210305 call 0.0092 GLOBEX USD>
<Option: JPY 20210305 call 0.0111 GLOBEX USD>
<Option: JPY 20210305 call 0.0107 GLOBEX USD>
<Option: JPY 20210305 call 0.0109 GLOBEX USD>
<Option: JPY 20210305 call 0.0121 GLOBEX USD>
<Option: JPY 20210305 call 0.0122 GLOBEX USD>
<Option: JPY 20210305 call 0.0123 GLOBEX USD>
<Option: JPY 20210305 call 0.0124 GLOBEX USD>
<Option: JPY 20210305 call 0.012 GLOBEX USD>
<Option: JPY 20210305 call 0.0076 GLOBEX USD>
<Option: JPY 20210305 call 0.0077 GLOBEX USD>
<Option: JPY 20210305 call 0.0078 GLOBEX USD>
<Option: JPY 20210305 call 0.0079 GLOBEX USD>
<Option: JPY 20210305 call 0.0074 GLOBEX USD>
<Option: JPY 20210305 call 0.0075 GLOBEX USD>
<Option: JPY 20210305 call 0.008 GLOBEX USD>
<Option: JPY 20210305 call 0.0081 GLOBEX USD>
<Option: JPY 20210305 call 0.0112 GLOBEX USD>
<Option: JPY 20210305 call 0.0117 GLOBEX USD>
<Option: JPY 20210305 call 0.0118 GLOBEX USD>
<Option: JPY 20210305 call 0.0119 GLOBEX USD>
<Option: JPY 20210305 call 0.0113 GLOBEX USD>
<Option: JPY 20210305 call 0.0114 GLOBEX USD>
<Option: JPY 20210305 call 0.0115 GLOBEX USD>
<Option: JPY 20210305 call 0.0116 GLOBEX USD>
<Option: JPY 20210305 call 0.01025 GLOBEX USD>
<Option: JPY 20210305 call 0.01035 GLOBEX USD>
<Option: JPY 20210305 call 0.0072 GLOBEX USD>
<Option: JPY 20210305 call 0.0073 GLOBEX USD>
<Option: JPY 20210305 call 0.00905 GLOBEX USD>
<Option: JPY 20210305 call 0.00895 GLOBEX USD>
<Option: JPY 20210305 call 0.00875 GLOBEX USD>
<Option: JPY 20210305 call 0.00885 GLOBEX USD>
<Option: JPY 20210305 call 0.00865 GLOBEX USD>
<Option: JPY 20210305 call 0.009375 GLOBEX USD>
<Option: JPY 20210305 call 0.009275 GLOBEX USD>
<Option: JPY 20210305 call 0.009475 GLOBEX USD>
<Option: JPY 20210305 call 0.009575 GLOBEX USD>
<Option: JPY 20210305 call 0.009325 GLOBEX USD>
<Option: JPY 20210305 call 0.009525 GLOBEX USD>
<Option: JPY 20210305 call 0.009675 GLOBEX USD>
<Option: JPY 20210305 call 0.009425 GLOBEX USD>
<Option: JPY 20210305 call 0.009625 GLOBEX USD>
<ContractDataEnd: request_id 1364 >
 => [#<IB::FutureOption:0x00000000017aac78 @metadata={}, @attributes={:symbol=>"JPY", :sec_type=>"FOP", :last_tra... 
3.0.0 :008 > 
```
Then choose the option of your interest.

```ruby
3.0.0 :010 > z[1].strike
 => 0.0104 
3.0.0 :011 > z[1].market_price
No subscribers for message IB::Messages::Incoming::MarketDataType!
TWS Warning 10167: Requested market data is not subscribed. Displaying delayed market data.
No subscribers for message IB::Messages::Incoming::TickRequestParameters!
 => 5.0e-06 
```

**Comment by JothamB** [comment]
i was able to work something out:

`c = (IB::FutureOption.new(symbol: "JPY", exchange: "GLOBEX", trading_class: "JPU", expiry: "20210305", right: "C")).verify.find {|o| o.attributes[:strike] == 0.00965}`

gives me the contract and i get a stream of correct data:

2021-02-10 06:22:09 -0500	5118	{:version=>6, :ticker_id=>5118, :tick_type=>1, :price=>1.7e-05, :size=>568, :can_auto_execute=>1}
2021-02-10 06:22:09 -0500	5118	{:version=>6, :ticker_id=>5118, :tick_type=>2, :price=>1.9e-05, :size=>40, :can_auto_execute=>1}

2021-02-10 06:22:14 -0500	1434	{:version=>6, :ticker_id=>1434, :tick_type=>1, :price=>1.7e-05, :size=>568, :can_auto_execute=>1}
2021-02-10 06:22:14 -0500	1434	{:version=>6, :ticker_id=>1434, :tick_type=>2, :price=>1.9e-05, :size=>40, :can_auto_execute=>1}

2021-02-10 06:22:19 -0500	293	{:version=>6, :ticker_id=>293, :tick_type=>1, :price=>1.7e-05, :size=>568, :can_auto_execute=>1}
2021-02-10 06:22:19 -0500	293	{:version=>6, :ticker_id=>293, :tick_type=>2, :price=>1.9e-05, :size=>40, :can_auto_execute=>1}

i can work with it but the problem is i have to add custom code to handle JPY futures options.
furthermore, each verify call floods the api with requests and i may hit the 50 request per seconds limit.

why is the problem with JPY futures options ? why do i have to use verify and find in array only for this class of contracts ?

**Comment by topofocus** [comment]
Are you sure that 50 requests per second limits the usage if reqContractDetail? I thought this limits the request for market-data. 

`Contract.verify{|c| c if (1 .. 6).include? c.strike }`

returns just a subset of the hole option-chain.

There are utility functions `atm`, `itm` and `otm`, which return just the nearest strikes. Take a look to the documentation.

**Comment by JothamB** [comment]
i bypassed the problem using the verify method and finding the appropriate option in the array.

yet, the problem persists.
after creating a FutureOption object with specific expiry strike and type, i expect a contract object and yet i get an array.

as i said, with a few more lines of code im able to get what i want.
i dont depend on a solution for this issue.
at this point, im merely a satisfied user of an open source project who does his civic duty and report an issue.

**Comment by JothamB** [comment]
i look into this issue and i want to share the findings with you.

the problem is with `socket.send_messages self.preprocess` in abstract_message.rb.

when i call :RequestContractData for `IB::FutureOption.new(symbol: "EUR", exchange: "GLOBEX", trading_class: "EUU", expiry: "20210305", strike: 1.22, right: "C")` the output of the method is:
`[9, 8, 1828, "", "EUR", "FOP", "20210305", 1.22, "C", "", "GLOBEX", "", "", "", "EUU", 0, "", ""]`

when i call :RequestContractData for `IB::FutureOption.new(symbol: "JPY", exchange: "GLOBEX", trading_class: "JPU", expiry: "20210305", strike: 0.0095, right: "C")` the output of the method is:
`[9, 8, 7166, "", "JPY", "FOP", "20210305", "", "C", "", "GLOBEX", "", "", "", "JPU", 0, "", ""]`

note that there is no strike between the strike and the right for the JPY option.

i took care of it be adding this code to replace to call to the preprocess method:

`message = self.preprocess`
`message[7] = self.data[:contract][:strike] if (self.class.name == "IB::Messages::Outgoing::RequestContractData" || self.class.name == "IB::Messages::Outgoing::RequestMarketData" || self.class.name == "IB::Messages::Outgoing::PlaceOrder") && self.data[:contract][:symbol] == "JPY" && self.data[:contract][:sec_type] == "FOP"`
`socket.send_messages message`

i dont understand the code good enough to fix the encoding problem itself.
i believe you can easily fix it.
my guts tell me this is because JPY futures options have very small fractions for strikes and the api and/or ruby handle these values in scientific notation (ie 0.1 = 1e-1)

if you have questions or if you need my data subscription im here and happy to talk.

**Comment by topofocus** [comment]
Hi,
thanks for your submission.

found the error.

its Contract.serialize

```ruby
 def serialize *fields  # :nodoc:
      print_default = ->(field, default="") { field.blank? ? default : field }
      print_not_zero = ->(field, default="") { field.to_i.zero? ? default : field }
      [(con_id.present? && !con_id.is_a?(Symbol) && con_id.to_i > 0 ? con_id : ""),
       print_default[symbol],
       print_default[self[:sec_type]],
       ( fields.include?(:option) ?
       [ print_default[expiry],  
	 print_not_zero[strike],     # <------    have to test if it can be substituted by print_default
	 print_default[self[:right]], 
	 print_default[multiplier]] : nil ),
       print_default[exchange],
       ( fields.include?(:primary_exchange) ? print_default[primary_exchange]   : nil ) ,
       print_default[currency]  ...
```

In the meantime you might edit the source

**Comment by topofocus** [comment]
Fixed the issue:

in the console of ib-extentions
```ruby
 c = IB::FutureOption.new(symbol: "JPY", exchange: "GLOBEX", trading_class: "JPU", expiry: "20210305", stri
ke: 0.01, right: "C")
 => #<IB::FutureOption:0x00007fea9ec590a0 @attributes={:symbol=>"JPY", :exchange=>"GLOBEX", :trading_class=>"JPU"... 
3.0.0 :004 > c.verify.to_human
 => ["<Option: JPY 20210305 call 0.01 GLOBEX USD>"] 

```

There is now strikt checking of zero. 
A zero-strike-option is retrieved via `Option.new ... strike: '0' `

The complete option chain is still available through `strike: 0` or simply by omitting the argument.
