### ISSUE TITLE
Clarification on status of project. Abandoned?

### ISSUE THREAD

**Issue by jumper444** [ib-ruby/ib-api#33]
IB's API is now 10.19 (stable; with 'latest' 10.28).
This project doesn't show recent development.
A last commit for VERSION file is "Update to Version 972.5.2" (aka v9.72).

As a person looking at the project there are different possibilities:
1) there are no significant changes that IB has made (doubtful with in a major version bump?) and this project still works fine unchanged (but there is no such note which would be reassuring); or
2) whatever was added to v10 is simply not supported by this project but previous stuff still works fine (again, no note though);
3) nobody is really using it and nobody really knows if there are issues with v10;

What I was hoping to see wouldn't be much more than a single sentence with a reasonably recent date.
That would be somebody (a contributor, developer ideally) saying something like:

"i'm still using this project; i'm using it with latest API v10.19; there do not seem to be any outstanding issues (although X, Y, and Z that IB changed/added are not supported); but of course disclaimer you are using at your own risk as with any such software"

So, I'm simply asking for a heartbeat/read on things if I might.

**Comment by jumper444** [comment]
PS: if ruby/IB devs moved to a different GEM or project I'd be interested as well. I'm not aware of one, but maybe I'm missing it.

**Comment by topofocus** [comment]
Hi,
I am still using ib-ruby in production.
Currently I am focused on other projects, thus the lack of developement.
The Gem works as expected with recent IB-API's.
I am using the gem for order placement, fetching price data and automated options-spread-selection. The pages at https://estx.hieron-y-mus.de cover the most recent open source activities backed by ib-ruby.

But I totally agree, the gem needs a face-lift.

I was planning to support the maybe project (https://github.com/maybe-finance/maybe), but this only makes sense, if some resources are available.

**Comment by jumper444** [comment]
I actually wasn't thinking anything needed a face-lift or development.
If it works then it works!   Say thanks and move on to other things in life would be my view.

I only thought the project would benefit from a small update to the top git page (the main page for the project) that says maybe (like you just said):  "As of March 2024 this Gem/code is still being used in production by some people (and against IB API v10) and continues to work properly as a stable/mature product by all appearances.  If anyone finds an issue or omission please submit it."

Anyway my point was that when I come upon a project that seems a bit dated where there hasn't been and API update or "all still running ok" note in a year or two (esp financial based) .... I get a bit uncertain.  Thanks for the reply.

**Comment by topofocus** [comment]
It works - you are right: never touch a running system.
BUT: I like the lightweight plugin technique if roda and want to adapt it here. 
Second: TWS-generated content should be immutable. 
and Third: implement BigDecimal instead of float to switch to the tws 10.xx branch.
