### ISSUE TITLE
Question: Can i use ib-api to just monitor for new orders / fills?

### ISSUE THREAD

**Issue by awunder** [ib-ruby/ib-api#9]
Hi,

Sry if this isnt the proper place (i was looking for a place to ask a q and your doc says _General support is provided through IB-Ruby Github-pages_)

i am looking for a ruby implementation to monitor a financial advisor account (its sub accounts) for new orders / fills and want to store them in a rails model..

The use case would be:

1. fire up a tws gateway on a server
2. connect ib-api(?) to that gateway (read-only) and let it wait for new orders
3. a user opens up the TWS somewhere and creates a new order
4. ib-api realizes that new order and stores it in the db
5. when the order gets filled / canceled, ib-api gets this message too and updates the order in the db

is ib-api the right tool for the job?

thanks so much!
Andreas

**Comment by topofocus** [comment]
Hi Andreas,

tb-api is sufficient. Ensure to use the client_id  0.

If you work with ib-gateway, the orders are assigned to the users as well.
You should get results simply by opening  /bin/gateway.rb and monitor G.clients.orders.

If you intent to store the orders in a database, ensure to use a fresh database-connection on each item as the messages are processed concurrently.  

The adapter to orientdb is currently in development.

greetings from stuttgart

hartmut

**Comment by awunder** [comment]
Hi Hartmut,

thx for this, will have a deeper look then! if, then i will most probably encorporate that into a rails app with postgres as database.

Ha! habe selber jahrelang in stuurget gewohnt! 

Grüße,
Andreas

**Comment by topofocus** [comment]
Under this circumstances, I invite you, to work on a rails-adapter. 
The »old« ib-ruby realized that through an engine. I prefer to realized that with a simple railtie.

If you are interested, let me know  (topofocus@gmail.com)
